// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHWc-gZ0dPbkXFhqLblh0VVwFft5iOPYE',
    appId: '1:364251398287:web:847d70cbc9e6bb1e2c70fa',
    messagingSenderId: '364251398287',
    projectId: 'messaging-app-6100d',
    authDomain: 'messaging-app-6100d.firebaseapp.com',
    storageBucket: 'messaging-app-6100d.appspot.com',
    measurementId: 'G-CGQKLJXJHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEXZysFPZHWExKBC8wH143v-ljmAMd1vs',
    appId: '1:364251398287:android:aa222ff13992fed32c70fa',
    messagingSenderId: '364251398287',
    projectId: 'messaging-app-6100d',
    storageBucket: 'messaging-app-6100d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIeBY6Tb5JnGUP9THm4MLnfC5b1hXITM',
    appId: '1:364251398287:ios:37694e28290a4cfc2c70fa',
    messagingSenderId: '364251398287',
    projectId: 'messaging-app-6100d',
    storageBucket: 'messaging-app-6100d.appspot.com',
    iosClientId: '364251398287-3am5pelojo2pcv82ove7of694hosdc74.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvIeBY6Tb5JnGUP9THm4MLnfC5b1hXITM',
    appId: '1:364251398287:ios:37694e28290a4cfc2c70fa',
    messagingSenderId: '364251398287',
    projectId: 'messaging-app-6100d',
    storageBucket: 'messaging-app-6100d.appspot.com',
    iosClientId: '364251398287-3am5pelojo2pcv82ove7of694hosdc74.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAssessment',
  );
}
